#ifndef CONFIG_H
#define CONFIG_H

#define SMARTIV_WIFI_SSID "YOUR_WIFI_NAME"
#define SMARTIV_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SMARTIV_FIREBASE_API_KEY "YOUR_FIREBASE_API_KEY"
#define SMARTIV_FIREBASE_DATABASE_URL "https://YOUR_PROJECT-default-rtdb.firebaseio.com/"

#define SMARTIV_DEVICE_ID "YOUR_DEVICE_ID"

#define SMARTIV_THINGSPEAK_CHANNEL_ID 1234567UL
#define SMARTIV_THINGSPEAK_WRITE_API_KEY "YOUR_THINGSPEAK_WRITE_API_KEY"

#endif
